// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://xcuuoakwbaldbvnpfpsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdXVvYWt3YmFsZGJ2bnBmcHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjY4ODgsImV4cCI6MjA3MzQ0Mjg4OH0.r7MEkLLusq98Y6fWYtnYKz9XQk5eguOQUfUxRzvWuSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});